#!/usr/bin/env python3
"""
Drop your real photos into assets/media/images/, then run:

    python3 sync-photos.py

It scans the folder and writes assets/js/photos.js (the gallery list + the
photo map the scenes and video posters use).

Two ways to name files:

  1. Same name as a placeholder  →  e.g. 02-rose-portrait.jpg
     That photo replaces the placeholder EVERYWHERE: scene backgrounds,
     video posters and the gallery slot (caption stays the same).

  2. Any other name              →  e.g. IMG_1234.jpg
     It joins the gallery with a short caption; scenes keep their
     placeholders until you name a file after them.

No real photos yet? Nothing breaks — the 18 gradient placeholders stay.
"""
import os
import json

HERE = os.path.dirname(os.path.abspath(__file__))
IMG = os.path.join(HERE, "assets", "media", "images")
OUT = os.path.join(HERE, "assets", "js", "photos.js")
REAL = (".jpg", ".jpeg", ".png", ".webp")

# short, 2-3 word captions — keyed by the placeholder slot name
CAPS = {
    "01-selfie-nike-jacket": "That grin",
    "02-rose-portrait": "Golden hour",
    "03-cap-chair": "Simply you",
    "04-turban-coat": "One look",
    "05-butterfly": "Soft light",
    "06-naval-428": "Full frame",
    "07-valley-blazer": "Little things",
    "08-valley-portrait": "Quiet smile",
    "09-valley-wide": "Easy day",
    "10-cartoons": "Big smile",
    "11-cartoon-hoodie": "Your laugh",
    "12-cartoon-train": "Good times",
    "13-cartoon-nike": "Evening glow",
    "14-cartoon-naval": "Street light",
    "15-cartoon-night": "City night",
    "16-cartoon-headshot": "Centrestage",
    "17-terminus-day": "Daylight frame",
    "18-terminus-night": "Night magic",
    "19-extra-one": "One more",
    "20-extra-two": "Extra frame",
}
# for files named anything at all
SPARE = ["Just you", "That grin", "Us moment", "Golden hour",
         "One frame", "Simple day", "Big smile", "Candid one"]


def stem(name):
    return os.path.splitext(name)[0]


files = sorted(f for f in os.listdir(IMG) if f.lower().endswith(REAL))
slots = sorted(f for f in os.listdir(IMG) if f.lower().endswith(".svg"))

photos, imgmap, taken = [], {}, set()
for i, f in enumerate(files):
    s = stem(f)
    if s + ".svg" in slots:                       # same slot name → swap everywhere
        imgmap["assets/media/images/" + s + ".svg"] = "assets/media/images/" + f
        taken.add(s)
    caption = CAPS.get(s) or SPARE[i % len(SPARE)]
    photos.append({"src": "assets/media/images/" + f, "caption": caption})

# gallery stays full: their photos first, placeholders fill the empty slots
for s in (stem(x) for x in slots):
    if s in taken:
        continue
    photos.append({"src": "assets/media/images/" + s + ".svg",
                   "caption": CAPS.get(s, "One frame")})

with open(OUT, "w", encoding="utf-8") as fh:
    fh.write("// auto-generated by sync-photos.py — do not edit by hand\n")
    fh.write("var PHOTOS = " + json.dumps(photos, ensure_ascii=False, indent=2) + ";\n")
    fh.write("var IMGMAP = " + json.dumps(imgmap, ensure_ascii=False, indent=2) + ";\n")

real_n = len(files)
print("Found %d real photo(s), %d placeholder slot(s) swapped." % (real_n, len(imgmap)))
for f in files:
    print("  +", f)
if not real_n:
    print("  (none yet — the gradient placeholders keep every slot)")
print("\nWrote", os.path.relpath(OUT, HERE))
print("Refresh the page (or re-open the file) to see them.")
